name: Deploy Spring Boot App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot app
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build --platform=linux/amd64 -t my-spring-app .

      - name: Save Docker image to tar
        run: docker save my-spring-app > my-spring-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "my-spring-app.tar"
          target: "~/"

      - name: Deploy container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker load < ~/my-spring-app.tar
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d \
              -p 8080:8080 \
              --env-file ./spring.env \
              -v /home/ec2-user/keys/mindtunetts-3a6bb0c4449b.json:/app/mindtunetts.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/mindtunetts.json \
              --name spring-app \
              my-spring-app
